name: Build Android Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install

    - name: Patch react-native-purchases
      run: |
        # Add namespace to build.gradle instead of removing package from manifest
        if [ -f "node_modules/react-native-purchases/android/build.gradle" ]; then
          sed -i '/android {/a\    namespace "com.revenuecat.purchases.react"' node_modules/react-native-purchases/android/build.gradle
        fi

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Create google-services.json
      run: |
        if [ -n "${{ secrets.GOOGLE_SERVICES_JSON }}" ]; then
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' | base64 -d > android/app/google-services.json
        else
          echo '{
            "project_info": {
              "project_number": "123456789",
              "firebase_url": "https://greedgross.firebaseio.com",
              "project_id": "greedgross",
              "storage_bucket": "greedgross.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:abc123",
                  "android_client_info": {
                    "package_name": "con.ggnextlevel.app"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyDummy-Key"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > android/app/google-services.json
        fi

    - name: Create .env file
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

    - name: Create Keystore
      run: |
        keytool -genkey -v -keystore android/app/release.keystore \
          -storepass greedgross123 -alias greedandgross -keypass greedgross123 \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Greed and Gross,O=GreedGross,C=US" -noprompt

    # Clean Gradle cache
    - name: Clean Gradle Cache
      run: |
        cd android
        ./gradlew clean
        rm -rf ~/.gradle/caches/

    # Build APK
    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE=release.keystore -PMYAPP_UPLOAD_KEY_ALIAS=greedandgross -PMYAPP_UPLOAD_STORE_PASSWORD=greedgross123 -PMYAPP_UPLOAD_KEY_PASSWORD=greedgross123

    # Build AAB
    - name: Build Release AAB
      run: |
        cd android
        ./gradlew bundleRelease -PMYAPP_UPLOAD_STORE_FILE=release.keystore -PMYAPP_UPLOAD_KEY_ALIAS=greedandgross -PMYAPP_UPLOAD_STORE_PASSWORD=greedgross123 -PMYAPP_UPLOAD_KEY_PASSWORD=greedgross123

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab

    - name: Upload Mapping File
      uses: actions/upload-artifact@v4
      with:
        name: mapping
        path: android/app/build/outputs/mapping/release/

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          android/app/build/outputs/bundle/release/app-release.aab
          android/app/build/outputs/apk/release/app-release.apk
        tag: v${{ github.run_number }}
        name: Release Build ${{ github.run_number }}
        body: |
          ## 🚀 Release Build ${{ github.run_number }}

          ### 📱 Download
          - [app-release.aab](https://github.com/${{ github.repository }}/releases/download/v${{ github.run_number }}/app-release.aab)
          - [app-release.apk](https://github.com/${{ github.repository }}/releases/download/v${{ github.run_number }}/app-release.apk)

          ### 📋 Details
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true